import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./hooks/useAuth";

// Import Roboto
const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "700"], // thường dùng trong UI: regular, medium, bold
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Loyy_shopThoiTrangOnline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${roboto.variable} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
